Feature/6 implementación de capa repositorio
CatCodeSV/Place4All-Backend pull request #12
Opened 2023-03-02 14:09 UTC by alecsolace

Se implementa la capa repositorio de forma genérica. En caso de métodos especiales se puede extender de la Interfaz para crear nuevos repositorios. 
Se añade una clase Document de la que heredan todos los modelos que comparten Id y fecha de creación. De esta forma MongoDB los crea automáticamente e inserta los hijos correspondientes. (Ej. Al insertar un usuario no hace falta llamar al servicio de dirección para que añada la dirección del usuario, esto se hace automáticamente.)

Closing #6

2023-03-02 16:00 UTC, alecsolace commented on Repositories/MongoDBRepository.cs
> +        private protected string GetCollectionName(Type documentType) //revisar
Método que coge el nombre de la colección desde el decorador del modelo

2023-03-02 16:00 UTC, alecsolace commented on Models/Users.cs
> +    [BsonCollection("Users")]
Ejemplo de decorador para tomar el nombre de la colección

2023-03-02 19:51 UTC, CyberLaidy requested changes
revisamos Task y Async

2023-03-02 19:51 UTC, CyberLaidy commented on Controllers/FeaturesController.cs
> +        public async Task<ActionResult<List<Features>>> Get() => _featuresService.Get();
quitar el async y task

2023-03-02 19:51 UTC, CyberLaidy commented on Controllers/ReservationsController.cs
> +    public async Task<List<Reservations>> Get() => _reservationsService.Get();
quitar async y task

2023-03-02 19:51 UTC, CyberLaidy commented on Controllers/ReservationsController.cs
>      public async Task<List<Reservations>> GetUserReserva(string usuarioId) =>
quitar async y task

2023-03-02 19:51 UTC, CyberLaidy commented on Controllers/RestaurantsController.cs
> +        public async Task Search(IBuscaCiudad ciudad) => _servicioRestaurante.Search(ciudad);
quitar async y task

2023-03-02 19:51 UTC, CyberLaidy commented on Controllers/ReviewsController.cs
>      public async Task<ActionResult<List<Reviews>>> GetByRestaurant(string id)
quitar async y task

2023-03-02 19:51 UTC, CyberLaidy commented on Controllers/ReviewsController.cs
>      public async Task<ActionResult<List<Reviews>>> GetByUser(string id)
quitar async y task

2023-03-02 19:51 UTC, CyberLaidy commented on Controllers/UsersController.cs
>      [Route("UsersUsers")]
revisar la ruta

2023-03-02 19:51 UTC, CyberLaidy commented on Controllers/UsersController.cs
> +        public async Task<ActionResult<List<Users>>> Get() => _usersService.Get();
quitar async y task

2023-03-02 19:51 UTC, CyberLaidy commented on Models/Features.cs
>          public string? Description { get; set; }
la descripción tiene que ser obligatoria?

2023-03-02 19:51 UTC, CyberLaidy commented on Services/FeaturesService.cs
> +    public void Update(Features feature)
este no tendría que ser async Task?

2023-03-02 19:51 UTC, CyberLaidy commented on Services/IReviewsService.cs
> +    List<Reviews> GetByUser(string userId);
igual deberíamos poner Task en GetByUser y GetByRestaurant??

2023-03-02 19:51 UTC, CyberLaidy commented on Services/IRestaurantsService.cs
> +    List<Restaurants> Search(IBuscaCiudad busqueda);
Ponemos task?

2023-03-02 19:51 UTC, CyberLaidy commented on Services/IReviewsService.cs
> +    List<Reviews> GetByRestaurant(string restaurantId);
igual debemos poner Task en ambos?

2023-03-03 11:28 UTC, LauLau13 commented on Controllers/AddressesController.cs
> +    public ActionResult<List<Addresses>> Get() => _addressesService.Get();
¿Pq los get ya no son asíncronos?

2023-03-03 11:28 UTC, LauLau13 commented on Controllers/FeaturesController.cs
> +        public async Task<ActionResult<List<Features>>> Get() => _featuresService.Get();
Este Get es asyncrono pero no tiene un await, igual da error en un futuro

2023-03-03 11:28 UTC, LauLau13 commented on Controllers/ReservationsController.cs
> +    public async Task<List<Reservations>> Get() => _reservationsService.Get();
lo mismo que en features

2023-03-03 11:28 UTC, LauLau13 commented on Controllers/AddressesController.cs
> +        _addressesService.Update(address);
Pq se quita el Id? Al utilizar el Update? Es pq ahora estamos usando un método genérico de Services y se puede sin id?

2023-03-03 11:28 UTC, LauLau13 commented on Controllers/RestaurantsController.cs
> +        public async Task<ActionResult<List<Restaurants>>> Get() => _servicioRestaurante.Get();
same

2023-03-03 11:28 UTC, LauLau13 commented on Controllers/UsersController.cs
> +        public async Task<ActionResult<List<Users>>> Get() => _usersService.Get();
same

2023-03-03 11:28 UTC, LauLau13 commented on Models/Addresses.cs
> -        public string? Id { get; set; }
¿Los Id ahora estarán en la clase Document de la que heredan supongo?

2023-03-03 11:28 UTC, LauLau13 commented on Models/IDocument.cs
> +        DateTime CreatedAt { get; }
El createdAt no se setea? Es pq siempre pondremos de manera automática la fecha actual de la creación del objeto?

2023-03-03 11:28 UTC, LauLau13 commented on Program.cs
> +            builder.Services.AddTransient<IFeaturesService, FeaturesService>();
¿Pq ahora es AddTransient si crea el servicio cada vez que se solicita, es mejor que el AddSingleton que crea el servicio una sola vez?

2023-03-03 11:28 UTC, LauLau13 commented on Repositories/BsonCollectionAttribute.cs
> +    }
no entiendo esta clase :/

2023-03-03 11:38 UTC, alecsolace commented on Models/Features.cs
>          public string? Description { get; set; }
En este caso la he puesto para que la descripción sea opcional, por eso tiene el ? de nullable.

2023-03-03 11:39 UTC, alecsolace commented on Services/FeaturesService.cs
> +    public void Update(Features feature)
Tendría que ser Async pero no task porque no devuelve nada

2023-03-03 11:41 UTC, alecsolace commented on Services/IReviewsService.cs
> +    List<Reviews> GetByUser(string userId);
Fíjate en el método del servicio y verás que no es un método asíncrono.

2023-03-03 11:42 UTC, alecsolace commented on Controllers/AddressesController.cs
> +    public ActionResult<List<Addresses>> Get() => _addressesService.Get();
Ahora son Queriables que se pasan a Listas. En un futuro si lo necesitamos podemos pasarlos a asíncronos, pero ahora mismo no se muy bien como pasar de Queriable o Enumerable a asíncrono.

2023-03-03 11:42 UTC, alecsolace commented on Controllers/FeaturesController.cs
> +        public async Task<ActionResult<List<Features>>> Get() => _featuresService.Get();
El async es un error, hay que quitarlo

2023-03-03 11:43 UTC, alecsolace commented on Controllers/AddressesController.cs
> +        _addressesService.Update(address);
Era redundante pasar un id que ya se encuentra dentro del propio address. Puedes sacar ese id haciendo address.id. Se ha hecho así en todos los updates ahora.

2023-03-03 11:43 UTC, alecsolace commented on Models/Addresses.cs
> -        public string? Id { get; set; }
Correcto, ahora todos los modelos heredan de documento y por ende tienen todos Id y fecha de creación.

2023-03-03 11:44 UTC, alecsolace commented on Models/IDocument.cs
> +        DateTime CreatedAt { get; }
Se setea en el document.cs

2023-03-03 11:45 UTC, alecsolace commented on Repositories/BsonCollectionAttribute.cs
> +    }
Es una clase auxiliar que nos permite sacar el nombre de la colección de cada modelo gracias al decorador que está encima de cada una. Se emplea en el repositorio genérico.

2023-03-03 11:46 UTC, alecsolace commented on Program.cs
> +            builder.Services.AddTransient<IFeaturesService, FeaturesService>();
Aquí cojeo un poco. Puede ser un scoped mejor pero no estaría de más preguntarlo en un futuro. Por ahora se puede dejar así

2023-03-03 11:47 UTC, alecsolace commented
@CyberLaidy revisa los comentarios y quita los async que correspondan.

2023-03-03 13:01 UTC, CyberLaidy commented on Repositories/MongoDBRepository.cs
> +        private protected string GetCollectionName(Type documentType) //revisar
¿y por que es privado, igual nos interesa que sea public?

2023-03-03 13:03 UTC, CyberLaidy commented on Models/Features.cs
>          public string? Description { get; set; }
ok

2023-03-03 13:08 UTC, alecsolace commented on Controllers/UsersController.cs
>      [Route("UsersUsers")]
Correcto, ponla como Users

2023-03-03 13:11 UTC, CyberLaidy commented on Controllers/ReservationsController.cs
> +    public async Task<List<Reservations>> Get() => _reservationsService.Get();
quitamos async?

2023-03-03 13:11 UTC, CyberLaidy commented on Controllers/RestaurantsController.cs
> +        public async Task<ActionResult<List<Restaurants>>> Get() => _servicioRestaurante.Get();
quitamos async?

2023-03-03 13:11 UTC, CyberLaidy commented on Controllers/UsersController.cs
> +        public async Task<ActionResult<List<Users>>> Get() => _usersService.Get();
quitamos async?

2023-03-03 13:17 UTC, CyberLaidy commented on Services/FeaturesService.cs
> +    public void Update(Features feature)
public async void o public async?

2023-03-03 13:41 UTC, alecsolace commented on Services/FeaturesService.cs
> +    public void Update(Features feature)
Public async void

2023-03-03 13:42 UTC, alecsolace commented on Repositories/MongoDBRepository.cs
> +        private protected string GetCollectionName(Type documentType) //revisar
Solo se usa dentro de este archivo entonces no se necesita que sea publico. Recuerda que siempre hay que ser lo más restrictivo posible.

2023-03-03 18:02 UTC, alecsolace commented on Controllers/RestaurantsController.cs
> +        public async Task<ActionResult<List<Restaurants>>> Get() => _servicioRestaurante.Get();
@CyberLaidy falta quitar el async Task

2023-03-03 18:03 UTC, alecsolace commented on Controllers/ReviewsController.cs
>      public async Task<ActionResult<List<Reviews>>> GetByUser(string id)
@CyberLaidy Falta quitar el async task

2023-03-03 18:04 UTC, alecsolace commented on Controllers/UsersController.cs
> +        public async Task<ActionResult<List<Users>>> Get() => _usersService.Get();
@CyberLaidy Falta quitar Async Task

2023-03-03 18:36 UTC, CyberLaidy requested changes

2023-03-03 18:36 UTC, CyberLaidy commented on Controllers/RestaurantsController.cs
> +        public async Task<ActionResult<List<Restaurants>>> Get() => _servicioRestaurante.Get();
ok

2023-03-03 18:36 UTC, CyberLaidy commented on Controllers/ReviewsController.cs
>      public async Task<ActionResult<List<Reviews>>> GetByUser(string id)
ok

2023-03-03 18:36 UTC, CyberLaidy commented on Controllers/UsersController.cs
> +        public async Task<ActionResult<List<Users>>> Get() => _usersService.Get();
ok

2023-03-03 18:36 UTC, CyberLaidy commented on Controllers/UsersController.cs
> +        public async Task<ActionResult<List<Users>>> Get() => _usersService.Get();
ok

2023-03-03 19:48 UTC, merged