07_VerificacionJWT
CatCodeSV/Place4All-Backend pull request #13
Opened 2023-03-05 11:15 UTC by LauLau13

2023-03-06 13:26 UTC, alecsolace commented on Controllers/RestaurantsController.cs
>          }
Echale un vistazo a este método. Solo quieres devolver el restauante que entra pero con la dirección completa si no la tenía. No quieres devolver una lista entera de restaurantes ya que en ningún momento recoges más restaurantes de la BBDD.

2023-03-06 13:31 UTC, alecsolace commented on Controllers/UsersController.cs
> +        }
Revisa si tiene sentido tener como parametro de entrada un Objeto Users si desde el front solo se puede mandar un email y password de tipo string para autenticar. Revisa si el método login de abajo tiene sentido mantenerlo o si es mejor quitarlo.

2023-03-06 13:31 UTC, alecsolace commented on Models/Restaurants.cs
> +        }
Es esto necesario?

2023-03-06 13:33 UTC, alecsolace commented on Services/UsersService.cs
> +            return tokenHandler.WriteToken(token);
Revisa si aquí puedes devolver el usuario desde aquí en vez de solo el token para que el método authenticate del controlador pueda tener como parametros de entrada solo el mail y la password. Devolviendo un objeto { tokenHandler.WriteToken(token), user}

2023-03-06 13:34 UTC, alecsolace requested changes
Está bien pero falta limpiar comentarios que no se usan y darle una vuelta al método authenticate (y revisar si borrar el método login)

2023-03-06 16:59 UTC, LauLau13 commented on Models/Restaurants.cs
> +        }
Seguramente no, es posible que lo haya implementado probando cosas y luego se me haya olvidado borrarlo

2023-03-08 15:53 UTC, alecsolace approved these changes

2023-03-08 15:59 UTC, merged